// <auto-generated />
using System;
using Bridge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bridge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BridgeDbContext))]
    [Migration("20260430030353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bridge.Domain.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AssignedAt")
                        .HasColumnType("date")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_assignments_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_assignments_status");

                    b.HasIndex("EngineerId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_engineer_id_project_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("PeriodFrom")
                        .HasColumnType("date")
                        .HasColumnName("period_from");

                    b.Property<DateOnly>("PeriodTo")
                        .HasColumnType("date")
                        .HasColumnName("period_to");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_contracts_assignment_id");

                    b.HasIndex("PeriodTo")
                        .HasDatabaseName("ix_contracts_period_to");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Engineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvoidedWorkNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avoided_work_note");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PrimarySalesId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_sales_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_engineers");

                    b.HasIndex("PrimarySalesId")
                        .HasDatabaseName("ix_engineers_primary_sales_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_engineers_user_id");

                    b.ToTable("engineers", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.HasKey("Id")
                        .HasName("pk_engineer_preferred_categories");

                    b.HasIndex("EngineerId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_engineer_preferred_categories_engineer_id_category");

                    b.ToTable("engineer_preferred_categories", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id")
                        .HasName("pk_engineer_preferred_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_engineer_preferred_skills_skill_id");

                    b.HasIndex("EngineerId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_engineer_preferred_skills_engineer_id_skill_id");

                    b.ToTable("engineer_preferred_skills", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<int>("Years")
                        .HasColumnType("integer")
                        .HasColumnName("years");

                    b.HasKey("Id")
                        .HasName("pk_engineer_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_engineer_skills_skill_id");

                    b.HasIndex("EngineerId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_engineer_skills_engineer_id_skill_id");

                    b.ToTable("engineer_skills", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("OwnerSalesId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_sales_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("UnitPriceMax")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price_max");

                    b.Property<int>("UnitPriceMin")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price_min");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OwnerSalesId")
                        .HasDatabaseName("ix_projects_owner_sales_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.ProjectRequiredSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("RequiredYears")
                        .HasColumnType("integer")
                        .HasColumnName("required_years");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("requirement_type");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id")
                        .HasName("pk_project_required_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_project_required_skills_skill_id");

                    b.HasIndex("ProjectId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_required_skills_project_id_skill_id");

                    b.ToTable("project_required_skills", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_user_id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_name");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("Assignments")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_engineers_engineer_id");

                    b.HasOne("Bridge.Domain.Entities.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_projects_project_id");

                    b.Navigation("Engineer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Contracts")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_assignments_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Engineer", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Sales", "PrimarySales")
                        .WithMany("Engineers")
                        .HasForeignKey("PrimarySalesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_engineers_sales_primary_sales_id");

                    b.HasOne("Bridge.Domain.Entities.User", "User")
                        .WithOne("Engineer")
                        .HasForeignKey("Bridge.Domain.Entities.Engineer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineers_users_user_id");

                    b.Navigation("PrimarySales");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredCategory", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("PreferredCategories")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_preferred_categories_engineers_engineer_id");

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredSkill", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("PreferredSkills")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_preferred_skills_engineers_engineer_id");

                    b.HasOne("Bridge.Domain.Entities.Skill", "Skill")
                        .WithMany("EngineerPreferredSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_preferred_skills_skills_skill_id");

                    b.Navigation("Engineer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerSkill", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("Skills")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_skills_engineers_engineer_id");

                    b.HasOne("Bridge.Domain.Entities.Skill", "Skill")
                        .WithMany("EngineerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_skills_skills_skill_id");

                    b.Navigation("Engineer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Project", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Sales", "OwnerSales")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerSalesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_sales_owner_sales_id");

                    b.Navigation("OwnerSales");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.ProjectRequiredSkill", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Project", "Project")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_required_skills_projects_project_id");

                    b.HasOne("Bridge.Domain.Entities.Skill", "Skill")
                        .WithMany("ProjectRequiredSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_required_skills_skills_skill_id");

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Sales", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.User", "User")
                        .WithOne("Sales")
                        .HasForeignKey("Bridge.Domain.Entities.Sales", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Engineer", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("PreferredCategories");

                    b.Navigation("PreferredSkills");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Sales", b =>
                {
                    b.Navigation("Engineers");

                    b.Navigation("OwnedProjects");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Skill", b =>
                {
                    b.Navigation("EngineerPreferredSkills");

                    b.Navigation("EngineerSkills");

                    b.Navigation("ProjectRequiredSkills");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.User", b =>
                {
                    b.Navigation("Engineer");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
