// <auto-generated />
using System;
using Bridge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bridge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BridgeDbContext))]
    partial class BridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bridge.Domain.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AssignedAt")
                        .HasColumnType("date")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_assignments_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_assignments_status");

                    b.HasIndex("EngineerId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_engineer_id_project_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("PeriodFrom")
                        .HasColumnType("date")
                        .HasColumnName("period_from");

                    b.Property<DateOnly>("PeriodTo")
                        .HasColumnType("date")
                        .HasColumnName("period_to");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_contracts_assignment_id");

                    b.HasIndex("PeriodTo")
                        .HasDatabaseName("ix_contracts_period_to");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Engineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvoidedWorkNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avoided_work_note");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PrimarySalesId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_sales_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_engineers");

                    b.HasIndex("PrimarySalesId")
                        .HasDatabaseName("ix_engineers_primary_sales_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_engineers_user_id");

                    b.ToTable("engineers", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.HasKey("Id")
                        .HasName("pk_engineer_preferred_categories");

                    b.HasIndex("EngineerId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_engineer_preferred_categories_engineer_id_category");

                    b.ToTable("engineer_preferred_categories", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id")
                        .HasName("pk_engineer_preferred_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_engineer_preferred_skills_skill_id");

                    b.HasIndex("EngineerId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_engineer_preferred_skills_engineer_id_skill_id");

                    b.ToTable("engineer_preferred_skills", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer")
                        .HasColumnName("engineer_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<int>("Years")
                        .HasColumnType("integer")
                        .HasColumnName("years");

                    b.HasKey("Id")
                        .HasName("pk_engineer_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_engineer_skills_skill_id");

                    b.HasIndex("EngineerId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_engineer_skills_engineer_id_skill_id");

                    b.ToTable("engineer_skills", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("OwnerSalesId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_sales_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("UnitPriceMax")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price_max");

                    b.Property<int>("UnitPriceMin")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price_min");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OwnerSalesId")
                        .HasDatabaseName("ix_projects_owner_sales_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.ProjectRequiredSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("RequiredYears")
                        .HasColumnType("integer")
                        .HasColumnName("required_years");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("requirement_type");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id")
                        .HasName("pk_project_required_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_project_required_skills_skill_id");

                    b.HasIndex("ProjectId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_required_skills_project_id_skill_id");

                    b.ToTable("project_required_skills", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_user_id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_name");

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Language",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Language",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Language",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Language",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Language",
                            Name = "Java"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Language",
                            Name = "Go"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Language",
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Language",
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Language",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Language",
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Framework",
                            Name = "React"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Framework",
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Framework",
                            Name = "Next.js"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Framework",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Framework",
                            Name = "Blazor"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Framework",
                            Name = "Spring Boot"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Framework",
                            Name = "Django"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Framework",
                            Name = "Ruby on Rails"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Framework",
                            Name = "Laravel"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Framework",
                            Name = "Express"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Infrastructure",
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Infrastructure",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Infrastructure",
                            Name = "GCP"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Infrastructure",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Infrastructure",
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Infrastructure",
                            Name = "Terraform"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Infrastructure",
                            Name = "Linux"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Database",
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Database",
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Database",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Database",
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Database",
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Database",
                            Name = "Redis"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Domain",
                            Name = "金融"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Domain",
                            Name = "製造"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Domain",
                            Name = "医療"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Domain",
                            Name = "小売・EC"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Domain",
                            Name = "通信"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Domain",
                            Name = "公共・官公庁"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Role",
                            Name = "PM"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Role",
                            Name = "PMO"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Role",
                            Name = "テックリード"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Role",
                            Name = "アーキテクト"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Role",
                            Name = "要件定義"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Role",
                            Name = "基本設計"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Role",
                            Name = "詳細設計"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Role",
                            Name = "コンサルタント"
                        },
                        new
                        {
                            Id = 48,
                            Category = "ProductType",
                            Name = "Web開発"
                        },
                        new
                        {
                            Id = 49,
                            Category = "ProductType",
                            Name = "業務系システム"
                        },
                        new
                        {
                            Id = 50,
                            Category = "ProductType",
                            Name = "パッケージ導入"
                        },
                        new
                        {
                            Id = 51,
                            Category = "ProductType",
                            Name = "運用保守"
                        },
                        new
                        {
                            Id = 52,
                            Category = "ProductType",
                            Name = "モバイルアプリ"
                        },
                        new
                        {
                            Id = 53,
                            Category = "ProductType",
                            Name = "組込・IoT"
                        },
                        new
                        {
                            Id = 54,
                            Category = "ProductType",
                            Name = "データ分析"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Tool",
                            Name = "Git"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Tool",
                            Name = "Jira"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Tool",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Tool",
                            Name = "Slack"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Tool",
                            Name = "GitHub"
                        });
                });

            modelBuilder.Entity("Bridge.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("Assignments")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_engineers_engineer_id");

                    b.HasOne("Bridge.Domain.Entities.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_projects_project_id");

                    b.Navigation("Engineer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Contracts")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_assignments_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Engineer", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Sales", "PrimarySales")
                        .WithMany("Engineers")
                        .HasForeignKey("PrimarySalesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_engineers_sales_primary_sales_id");

                    b.HasOne("Bridge.Domain.Entities.User", "User")
                        .WithOne("Engineer")
                        .HasForeignKey("Bridge.Domain.Entities.Engineer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineers_users_user_id");

                    b.Navigation("PrimarySales");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredCategory", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("PreferredCategories")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_preferred_categories_engineers_engineer_id");

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerPreferredSkill", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("PreferredSkills")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_preferred_skills_engineers_engineer_id");

                    b.HasOne("Bridge.Domain.Entities.Skill", "Skill")
                        .WithMany("EngineerPreferredSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_preferred_skills_skills_skill_id");

                    b.Navigation("Engineer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.EngineerSkill", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Engineer", "Engineer")
                        .WithMany("Skills")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_skills_engineers_engineer_id");

                    b.HasOne("Bridge.Domain.Entities.Skill", "Skill")
                        .WithMany("EngineerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_engineer_skills_skills_skill_id");

                    b.Navigation("Engineer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Project", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Sales", "OwnerSales")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerSalesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_sales_owner_sales_id");

                    b.Navigation("OwnerSales");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.ProjectRequiredSkill", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.Project", "Project")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_required_skills_projects_project_id");

                    b.HasOne("Bridge.Domain.Entities.Skill", "Skill")
                        .WithMany("ProjectRequiredSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_required_skills_skills_skill_id");

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Sales", b =>
                {
                    b.HasOne("Bridge.Domain.Entities.User", "User")
                        .WithOne("Sales")
                        .HasForeignKey("Bridge.Domain.Entities.Sales", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Engineer", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("PreferredCategories");

                    b.Navigation("PreferredSkills");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Sales", b =>
                {
                    b.Navigation("Engineers");

                    b.Navigation("OwnedProjects");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.Skill", b =>
                {
                    b.Navigation("EngineerPreferredSkills");

                    b.Navigation("EngineerSkills");

                    b.Navigation("ProjectRequiredSkills");
                });

            modelBuilder.Entity("Bridge.Domain.Entities.User", b =>
                {
                    b.Navigation("Engineer");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
